let token=localStorage.token||"", user=JSON.parse(localStorage.user||"null"), cart=JSON.parse(localStorage.cart||"[]");
const app=document.getElementById("app");
const money=n=>"₹"+Number(n).toLocaleString("en-IN",{maximumFractionDigits:0});
function headers(){return token?{Authorization:"Bearer "+token,"Content-Type":"application/json"}:{"Content-Type":"application/json"}}
function save(){localStorage.cart=JSON.stringify(cart);document.getElementById("cartCount").textContent=cart.reduce((s,x)=>s+x.quantity,0)}
function toast(t){let x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function show(p){if(p==="home")home(); else if(p==="shop")shop(); else if(p==="login")login(); else if(p==="register")register(); else if(p==="orders")orders(); else if(p==="admin")admin(); else if(p==="about")about();}
async function home(){app.innerHTML=`<section class="hero"><div><span class="tag">FRESH • LOCAL • DELIVERED</span><h1>Nature's best,<br>delivered fresh.</h1><p>Hand-picked fruits sourced for homes across Telangana. Simple ordering, fresh quality and doorstep convenience.</p><button class="btn" onclick="show('shop')">Shop Fresh Fruits →</button></div></section><section class="section"><h2>Popular today</h2><div id="homegrid" class="grid"></div></section>`;let p=await fetch("/api/products").then(r=>r.json());renderGrid(p.slice(0,4),"homegrid")}
async function shop(){app.innerHTML=`<section class="section"><h2>Fresh fruit market</h2><div class="toolbar"><input id="search" class="input" placeholder="Search fruits..." oninput="filterShop()"><select id="cat" class="select" onchange="filterShop()"><option value="">All categories</option><option>Mango</option><option>Banana</option><option>Apple</option><option>Orange</option><option>Grapes</option><option>Melon</option><option>Pomegranate</option><option>Papaya</option></select></div><div id="shopgrid" class="grid"></div></section>`;window.products=await fetch("/api/products").then(r=>r.json());renderGrid(window.products,"shopgrid")}
function filterShop(){let q=document.getElementById("search").value.toLowerCase(),c=document.getElementById("cat").value;renderGrid(window.products.filter(x=>(x.name+x.category).toLowerCase().includes(q)&&(!c||x.category===c)),"shopgrid")}
function renderGrid(list,id){document.getElementById(id).innerHTML=list.map(p=>`<article class="card"><img src="${p.image}" alt="${p.name}"><div class="cardbody"><span class="tag">${p.category}</span><h3>${p.name}</h3><div class="muted">${p.description}</div><div class="row"><div><div class="price">${money(p.price)}</div><span class="muted">${p.unit} • ${p.stock} available</span></div><button class="btn" onclick='add(${p.id})'>Add</button></div></div></article>`).join("")||"<p>No fruits found.</p>"}
async function add(id){let p=(window.products||[]).find(x=>x.id===id);if(!p)p=await fetch("/api/products").then(r=>r.json()).then(a=>a.find(x=>x.id===id));let x=cart.find(x=>x.product_id===id);if(x)x.quantity++;else cart.push({product_id:id,name:p.name,price:p.price,image:p.image,unit:p.unit,quantity:1});save();toast("Added to cart")}
function openCart(){let total=cart.reduce((s,x)=>s+x.price*x.quantity,0);document.getElementById("modal").classList.remove("hidden");document.getElementById("modal").innerHTML=`<div class="drawer"><div class="row"><h2>Your basket</h2><button onclick="closeModal()">✕</button></div>${cart.length?cart.map((x,i)=>`<div class="order row"><div><b>${x.name}</b><div class="muted">${x.unit}</div></div><div><button onclick="qty(${i},-1)">−</button> ${x.quantity} <button onclick="qty(${i},1)">+</button> <b>${money(x.price*x.quantity)}</b></div></div>`).join(""):`<p>Your basket is empty.</p>`}<div class="row"><h3>Total</h3><h2>${money(total)}</h2></div>${cart.length?`<button class="btn" style="width:100%" onclick="checkout()">Proceed to checkout</button>`:""}</div>`}
function qty(i,d){cart[i].quantity+=d;if(cart[i].quantity<=0)cart.splice(i,1);save();openCart()}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function login(){app.innerHTML=`<div class="panel"><h2>Welcome back</h2><p class="muted">Customer and admin accounts use the same secure login.</p><input id="email" placeholder="Email"><input id="pass" type="password" placeholder="Password"><button class="btn" onclick="doLogin()">Login</button><p>New customer? <a href="#" onclick="show('register')">Create account</a></p><hr><small>Admin demo: admin@sthfreshfruit.in / Admin@123</small></div>`}
async function doLogin(){let r=await fetch("/api/login",{method:"POST",headers:headers(),body:JSON.stringify({email:email.value,password:pass.value})}),d=await r.json();if(!r.ok)return toast(d.error);token=d.token;user=d.user;localStorage.token=token;localStorage.user=JSON.stringify(user);toast("Login successful");show(user.role==="admin"?"admin":"home")}
function register(){app.innerHTML=`<div class="panel"><h2>Create your account</h2><input id="name" placeholder="Full name"><input id="phone" placeholder="Phone number"><input id="email" placeholder="Email"><input id="pass" type="password" placeholder="Password"><button class="btn" onclick="doRegister()">Create account</button><p>Already registered? <a href="#" onclick="show('login')">Login</a></p></div>`}
async function doRegister(){let r=await fetch("/api/register",{method:"POST",headers:headers(),body:JSON.stringify({name:name.value,phone:phone.value,email:email.value,password:pass.value})}),d=await r.json();if(!r.ok)return toast(d.error);token=d.token;user=d.user;localStorage.token=token;localStorage.user=JSON.stringify(user);show("home")}
function checkout(){if(!token){closeModal();show("login");return}document.getElementById("modal").innerHTML=`<div class="drawer"><h2>Checkout</h2><textarea id="address" rows="4" placeholder="Delivery address in Telangana"></textarea><button class="btn" style="width:100%" onclick="placeOrder()">Pay online / UPI</button></div>`}
async function placeOrder(){let r=await fetch("/api/orders",{method:"POST",headers:headers(),body:JSON.stringify({items:cart.map(x=>({product_id:x.product_id,quantity:x.quantity})),address:address.value})}),d=await r.json();if(!r.ok)return toast(d.error);if(d.razorpay_order_id&&window.Razorpay){let rz=new Razorpay({key:d.key_id,amount:Math.round(d.total*100),currency:"INR",name:"STH Fresh Fruit",description:"Fresh fruit order",order_id:d.razorpay_order_id,handler:async()=>{await fetch("/api/orders/"+d.order_id+"/paid",{method:"POST",headers:headers()});cart=[];save();closeModal();toast("Payment successful");show("orders")}});rz.open()}else{cart=[];save();closeModal();toast("Order placed. Configure Razorpay keys for live UPI.");show("orders")}}
async function orders(){if(!token)return show("login");let a=await fetch("/api/orders",{headers:headers()}).then(r=>r.json());app.innerHTML=`<section class="section"><h2>My orders</h2>${a.map(o=>`<div class="order"><div class="row"><b>Order #${o.id}</b><span class="tag">${o.order_status}</span></div><p>${o.items.map(x=>x.name+" × "+x.quantity).join(", ")}</p><div class="row"><span class="muted">${o.payment_status}</span><b>${money(o.total)}</b></div></div>`).join("")||"<p>No orders yet.</p>"}</section>`}
async function admin(){if(!user||user.role!=="admin")return show("login");app.innerHTML=`<section class="section"><h2>Admin dashboard</h2><div id="stats" class="grid"></div><div class="adminnav"><button class="btn" onclick="adminProducts()">Products</button><button class="btn" onclick="adminOrders()">Orders</button><button class="btn light" onclick="logout()">Logout</button></div><div id="adminarea"></div></section>`;let s=await fetch("/api/admin/stats",{headers:headers()}).then(r=>r.json());document.getElementById("stats").innerHTML=[["Products",s.products],["Customers",s.customers],["Orders",s.orders],["Paid sales",money(s.sales)]].map(x=>`<div class="card"><div class="cardbody"><span class="muted">${x[0]}</span><h2>${x[1]}</h2></div></div>`).join("");adminProducts()}
async function adminProducts(){let a=await fetch("/api/admin/products",{headers:headers()}).then(r=>r.json());document.getElementById("adminarea").innerHTML=`<div class="panel" style="max-width:none"><h3>Add product</h3><div class="toolbar"><input id="pn" class="input" placeholder="Fruit name"><input id="pc" class="input" placeholder="Category"><input id="pp" class="input" placeholder="Price"><input id="pu" class="input" placeholder="Unit (1 kg)"><input id="pi" class="input" placeholder="Image URL"><input id="ps" class="input" placeholder="Stock"></div><button class="btn" onclick="addProduct()">Add fruit</button></div><div class="panel" style="max-width:none"><h3>Inventory</h3><table class="table"><tr><th>Fruit</th><th>Price</th><th>Stock</th><th>Action</th></tr>${a.map(p=>`<tr><td>${p.name}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><button onclick="delProduct(${p.id})">Delete</button></td></tr>`).join("")}</table></div>`}
async function addProduct(){let body={name:pn.value,category:pc.value,price:pp.value,unit:pu.value,image:pi.value,stock:ps.value};let r=await fetch("/api/admin/products",{method:"POST",headers:headers(),body:JSON.stringify(body)});if(r.ok){toast("Product added");adminProducts()}}
async function delProduct(id){if(!confirm("Delete this product?"))return;await fetch("/api/admin/products/"+id,{method:"DELETE",headers:headers()});adminProducts()}
async function adminOrders(){let a=await fetch("/api/admin/orders",{headers:headers()}).then(r=>r.json());document.getElementById("adminarea").innerHTML=`<div class="panel" style="max-width:none"><h3>Orders</h3><table class="table"><tr><th>#</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Update</th></tr>${a.map(o=>`<tr><td>${o.id}</td><td>${o.name}<br>${o.email}</td><td>${money(o.total)}</td><td>${o.payment_status}</td><td>${o.order_status}</td><td><select onchange="updateOrder(${o.id},this.value)"><option>PLACED</option><option>CONFIRMED</option><option>PACKED</option><option>OUT FOR DELIVERY</option><option>DELIVERED</option></select></td></tr>`).join("")}</table></div>`}
async function updateOrder(id,status){await fetch("/api/admin/orders/"+id,{method:"PUT",headers:headers(),body:JSON.stringify({order_status:status,payment_status:"PAID"})});toast("Order updated")}
function logout(){localStorage.clear();token="";user=null;cart=[];save();show("home")}
function about(){app.innerHTML=`<section class="section"><h2>Freshness you can trust</h2><p>STH Fresh Fruit is designed for convenient fruit delivery across Telangana.</p></section>`}
save();home();
